# Generated by Django 5.2 on 2025-11-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created']},
        ),
    ]
